# Generated by Django 5.0.4 on 2025-02-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_position_alter_customuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
