# Generated by Django 5.0.4 on 2025-01-28 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnoverdocument',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
