# Generated by Django 5.0.4 on 2025-01-28 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_turnoverdocument_publish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnoverdocument',
            options={'ordering': ['-publish']},
        ),
        migrations.RemoveIndex(
            model_name='turnoverdocument',
            name='blog_turnov_created_bd7545_idx',
        ),
        migrations.AddIndex(
            model_name='turnoverdocument',
            index=models.Index(fields=['-publish'], name='blog_turnov_publish_57758b_idx'),
        ),
    ]
