# Generated by Django 5.0.4 on 2025-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_turnoverdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoverdocument',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('UR', 'UnderReview'), ('A', 'Approved'), ('R', 'Rejected'), ('PB', 'Published')], default='DF', max_length=2),
        ),
    ]
