# Generated by Django 5.0.4 on 2025-01-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_turnoverdocument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoverdocument',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='published'),
        ),
    ]
