# Generated by Django 5.0.4 on 2025-01-31 22:10

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_turnoverdocument_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnoverdocument',
            options={'ordering': ['-publish_by']},
        ),
        migrations.AlterModelManagers(
            name='turnoverdocument',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='turnoverdocument',
            name='blog_turnov_publish_57758b_idx',
        ),
        migrations.RenameField(
            model_name='turnoverdocument',
            old_name='publish',
            new_name='publish_by',
        ),
        migrations.AlterField(
            model_name='turnoverdocument',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('UR', 'Under Review'), ('A', 'Approved'), ('R', 'Rejected'), ('PB', 'Published')], default='DF', max_length=2),
        ),
        migrations.AddIndex(
            model_name='turnoverdocument',
            index=models.Index(fields=['-publish_by'], name='blog_turnov_publish_5aa0a7_idx'),
        ),
    ]
