# Generated by Django 5.0.4 on 2025-02-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_turnoverdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='turnoverdocument',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='turnoverdocument',
            name='document_file',
            field=models.FileField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='turnoverdocument',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish_by'),
        ),
    ]
