# Generated by Django 5.0.4 on 2025-02-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_turnoverdocument_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoverdocument',
            name='document_file',
            field=models.FileField(upload_to='blog/static/images/'),
        ),
    ]
