# Generated by Django 5.0.4 on 2025-02-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='due_date',
        ),
    ]
