# Generated by Django 5.0.4 on 2025-02-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/screenshots'),
        ),
    ]
