# Generated by Django 5.0.4 on 2025-03-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_accepted_at_alter_ticket_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
