# Generated by Django 5.0.4 on 2025-02-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_assigned_to_ticket_accepted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/static/ticket_image/'),
        ),
    ]
