# Generated by Django 5.0.4 on 2025-03-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_screenshot_ticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completion_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
